_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  node__add_page:
    enabled: false
    menu_name: tools
    parent: ''
    expanded: false
    weight: 0
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: 2
